#!/bin/bash
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --time=07:59:00
#SBATCH --job-name=nlp_scibert
#SBATCH --mem=82GB
#SBATCH --ntasks=1
#SBATCH --output=myjob.%j.out
#SBATCH --error=myjob.%j.err

module load cuda/11.7
module load anaconda3/2022.05
source activate /home/phillippo.s/nlp_proj
python /home/phillippo.s/NLPProject/ProcessDataBuildDB.py /scratch/selvitelli.n/dataset/split_0 /home/phillippo.s/NLPProject/completed.txt
